apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "kong"
bases:
- ../base/
resources:
- service.yaml
patches:
- path: patches.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: ingress-kong
